build-docker:
  image:
    name: docker:24-cli
    pull_policy: if-not-present
  stage: build
  tags:
    - dind
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --name mybuilder --use
  script: docker buildx build
    --push
    --platform linux/amd64
    --tag $IMAGE_NAME
    .
  only:
    - tags
