build-docker:
  image: docker:24-cli
  stage: build
  tags:
    - dind
  services:
    - docker:24-dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --name mybuilder --use
  script: docker buildx build
    --push
    --platform linux/amd64
    --tag $IMAGE_NAME:$CI_COMMIT_TAG
    .
  only:
    - tags
