build-docker:
  image:
    name: docker:24-cli
    pull_policy: always
  stage: build
  tags:
    - dind
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker buildx create --name mybuilder --use
  script:
    - docker buildx build --platform linux/amd64 --tag $DOCKER_IMAGE_NAME --load .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - tags
